server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=/identity/**
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=/profile/users/**
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=/notification/**